### ISSUE TITLE
Add preference to customize domain

### ISSUE THREAD

**Issue by edouard-lopez** [losnappas/Context-menu-dictionary#3]
Nice work :)
Sadly it focus on English wiktionary, I was expecting to be able to customize the domain through some settings (I'm French).

**Comment by losnappas** [comment]
Thanks.

Only took me 10 days to notice your posts here...

Currently the api only supports English wiktionary. 
https://en.wiktionary.org/api/rest_v1/#!/Page_content/get_page_definition_term
Imma try and keep track of this, in case it ever changes.

**Comment by losnappas** [comment]
There's now a thingy to choose a language in the preferences. Works differently than the English results, though. Opens the full Wiktionary page in the popup.

**Comment by edouard-lopez** [comment]
Great! Thanks :)
