### ISSUE TITLE
Other languages

### ISSUE THREAD

**Issue by edouard-lopez** [losnappas/Context-menu-dictionary#5]
Cheer and keep the good work.

You should improve the call-to-action by:
1. changing text on the <kbd>[+]</kbd> button to a label such as <kbd>show others languages</kbd> 
2. showing this button only when there is other languages

---
![selection_158](https://user-images.githubusercontent.com/1212392/35091276-66bcd21a-fc3c-11e7-9a80-d8ed38dd014c.png)

**Comment by losnappas** [comment]
When I was implementing the button, I thought whether to display a disabled button or not display it at all. I'll take your advice and it'll be in the next version. Hopefully tomorrow or Tuesday (30.).

ty
